export const TOGGLE_MENU = "TOGGLE_MENU"
export const TOGGLE_PROFILE_MENU = "TOGGLE_PROFILE_MENU"
export const TOGGLE_ADMIN_MENU = "TOGGLE_ADMIN_MENU"
export const TOGGLE_SEARCH = "TOGGLE_SEARCH"
export const TOGGLE_AUTH_MODAL = "TOGGLE_AUTH_MODAL"


export const TOGGLE_EDIT_USER = "TOGGLE_EDIT_USER"

export const TOGGLE_EDIT_USER_BEGIN = "TOGGLE_EDIT_USER_BEGIN"
export const TOGGLE_EDIT_USER_SUCCESS = "TOGGLE_EDIT_USER_SUCCESS"
export const TOGGLE_EDIT_USER_ERROR = "TOGGLE_EDIT_USER_ERROR"


export const QAUTH_BEGIN = "QAUTH_BEGIN"
export const QAUTH_SUCCESS = "QAUTH_SUCCESS"
export const QAUTH_ERROR = "QAUTH_ERROR"

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"


export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN "
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"


export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN"
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS"
export const GET_CURRENT_QUSER_SUCCESS = "GET_CURRENT_QUSER_SUCCESS"
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR "

export const GET_ADMIN_BEGIN = "    GET_ADMIN_BEGIN"
export const GET_ADMIN_SUCCESS = "    GET_ADMIN_SUCCESS"
export const GET_ADMIN_ERROR = "    GET_ADMIN_ERROR"


export const REGISTER_ADMIN_BEGIN = "REGISTER_ADMIN_BEGIN"
export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS"
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR"


export const LOGIN_ADMIN_BEGIN = "LOGIN_ADMIN_BEGIN "
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS"
export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR"


export const UPLOAD_ITEM_BEGIN = "UPLOAD_ITEM_BEGIN "
export const UPLOAD_ITEM_SUCCESS = "UPLOAD_ITEM_SUCCESS"
export const UPLOAD_ITEM_ERROR = "UPLOAD_ITEM_ERROR"

export const LOGOUT_USER = "LOGOUT_USER"
export const QLOGOUT_USER = "QLOGOUT_USER"


export const GET_PRODUCT_BEGIN = "GET_PRODUCT_BEGIN"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"

export const TOGGLE_THEME = "TOGGLE_THEME"

export const SAVE_PRODUCT_BEGIN = "SAVE_PRODUCT_BEGIN"
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS"
export const SAVE_PRODUCT_ERROR = "SAVE_PRODUCT_ERROR"

export const SAVED_PRODUCT_BEGIN = "SAVED_PRODUCT_BEGIN"
export const SAVED_PRODUCT_SUCCESS = "SAVED_PRODUCT_SUCCESS"
export const SAVED_PRODUCT_ERROR = "SAVED_PRODUCT_ERROR"



export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN"
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS"
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR"


export const PURCHASED_PRODUCT_BEGIN = "PURCHASED_PRODUCT_BEGIN"
export const PURCHASED_PRODUCT_SUCCESS = "PURCHASED_PRODUCT_SUCCESS"
export const PURCHASED_PRODUCT_ERROR = "PURCHASED_PRODUCT_ERROR"